<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Employees test suite"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="3.548">
    <properties></properties>

            <testcase
                name="verifyEmployees"
                time="1.057"
                classname="org.onefamily.AppTest">

            <failure type="java.lang.AssertionError" message="[Employees api should respond with status code 200] 
expected: 200
 but was: 429">
                <![CDATA[java.lang.AssertionError: [Employees api should respond with status code 200] 
expected: 200
 but was: 429
                org.onefamily.AppTest.verifyEmployees(AppTest.java:43)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:564)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:806)org.testng.TestRunner.run(TestRunner.java:601)org.testng.SuiteRunner.runTest(SuiteRunner.java:433)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)org.testng.SuiteRunner.run(SuiteRunner.java:330)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)org.testng.TestNG.runSuitesLocally(TestNG.java:1176)org.testng.TestNG.runSuites(TestNG.java:1099)org.testng.TestNG.run(TestNG.java:1067)org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </failure>
    </testcase>


            <testcase
                name="verifyEmployeeById"
                time="0.667"
                classname="org.onefamily.AppTest">
            </testcase>
            <testcase
                name="verifyEmployeeById"
                time="1.824"
                classname="org.onefamily.AppTest">
            </testcase>
</testsuite>
